version: '3.8'
name: "hello srk"
services:
  mongo:
    image : mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - hello-srk:/data/db


  backend:
     build:
       context: ./practice-ecommerce-ts
     container_name: backend    
     ports:
        - "5000:5000"
     environment:
          - PORT=5000
          - MONGO_URI=mongodb://mongo:27017/practiceE
          - JWT_SECRET=tttttttttt
     depends_on:
          - mongo

  frontend:
     build:
       context: ./practice-front
     container_name: frontend
     ports:
        - "5173:5173"
     depends_on:
          - backend
          
volumes:
  hello-srk:
    driver: local


