version: '3.8'
name: "hello-srk"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - hello-srk:/data/db

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  backend:
    build:
      context: ./back
    container_name: backend    
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/practiceE
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=tttttttttt
    depends_on:
      - mongo
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./back/package.json
        - action: rebuild
          path: ./back/package-lock.json
        - action: sync
          path: ./back
          target: /app

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./front/package.json
        - action: rebuild
          path: ./front/package-lock.json
        - action: sync
          path: ./front
          target: /app

volumes:
  hello-srk:
    driver: local
